// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockservice.proto

package bsp_transaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BspBlockRequest struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BspBlockRequest) Reset()         { *m = BspBlockRequest{} }
func (m *BspBlockRequest) String() string { return proto.CompactTextString(m) }
func (*BspBlockRequest) ProtoMessage()    {}
func (*BspBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_642d8e927c257900, []int{0}
}

func (m *BspBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BspBlockRequest.Unmarshal(m, b)
}
func (m *BspBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BspBlockRequest.Marshal(b, m, deterministic)
}
func (m *BspBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BspBlockRequest.Merge(m, src)
}
func (m *BspBlockRequest) XXX_Size() int {
	return xxx_messageInfo_BspBlockRequest.Size(m)
}
func (m *BspBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BspBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BspBlockRequest proto.InternalMessageInfo

func (m *BspBlockRequest) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BspBlockRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

// BlockResponse 's Payload contains MCHeader when it's GetMCBlockByNumber, or EC-Blcok for GetECBlockByNumber
type BlockResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	SignatureHeader      []byte   `protobuf:"bytes,3,opt,name=SignatureHeader,proto3" json:"SignatureHeader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_642d8e927c257900, []int{1}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BlockResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockResponse) GetSignatureHeader() []byte {
	if m != nil {
		return m.SignatureHeader
	}
	return nil
}

func init() {
	proto.RegisterType((*BspBlockRequest)(nil), "bsp_transaction.BspBlockRequest")
	proto.RegisterType((*BlockResponse)(nil), "bsp_transaction.BlockResponse")
}

func init() { proto.RegisterFile("blockservice.proto", fileDescriptor_642d8e927c257900) }

var fileDescriptor_642d8e927c257900 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x89, 0xca, 0xc8, 0x5c, 0x2b, 0x85, 0xbb, 0x90, 0x20, 0x22, 0x61, 0x56, 0x5d, 0x75,
	0xa1, 0x6f, 0x50, 0x11, 0x05, 0x51, 0x24, 0x03, 0x6e, 0x25, 0xe9, 0x5c, 0x86, 0xe0, 0x98, 0x64,
	0x92, 0x54, 0xe8, 0xcb, 0xf9, 0x6c, 0x62, 0x5a, 0xff, 0xea, 0x76, 0x96, 0xe7, 0x70, 0xf8, 0x92,
	0x8f, 0x0b, 0xa8, 0x37, 0xae, 0x7d, 0x89, 0x14, 0xde, 0x4c, 0x4b, 0xb5, 0x0f, 0x2e, 0x39, 0x2c,
	0x75, 0xf4, 0xcf, 0x29, 0x28, 0x1b, 0x55, 0x9b, 0x8c, 0xb3, 0x8b, 0x3b, 0x28, 0x9b, 0xe8, 0x9b,
	0xcf, 0xa5, 0xa4, 0x6d, 0x47, 0x31, 0xa1, 0x80, 0xa3, 0x9c, 0x1f, 0xba, 0x57, 0x4d, 0x81, 0x33,
	0xc1, 0xaa, 0x03, 0xf9, 0xbb, 0xc2, 0x13, 0x98, 0x49, 0x5a, 0x1b, 0x67, 0xf9, 0x9e, 0x60, 0xd5,
	0x5c, 0x8e, 0x69, 0xb1, 0x85, 0xe3, 0x91, 0x14, 0xbd, 0xb3, 0x91, 0x90, 0xc3, 0xe1, 0xa3, 0xea,
	0x37, 0x4e, 0xad, 0x32, 0xa6, 0x90, 0x5f, 0x11, 0xcf, 0x60, 0xbe, 0x34, 0x6b, 0xab, 0x52, 0x17,
	0x28, 0x53, 0x0a, 0xf9, 0x53, 0x60, 0x05, 0xe5, 0x77, 0xb8, 0x25, 0xb5, 0xa2, 0xc0, 0xf7, 0xf3,
	0x66, 0x5a, 0x5f, 0xbc, 0x33, 0x28, 0xf2, 0x9b, 0xcb, 0xc1, 0x13, 0x9f, 0x00, 0x6f, 0x28, 0xdd,
	0x5f, 0xe5, 0xb2, 0xe9, 0xc7, 0x1f, 0x8b, 0x7a, 0x22, 0x5e, 0x4f, 0xac, 0x4f, 0xcf, 0xff, 0x2f,
	0xfe, 0xa8, 0x0c, 0xdc, 0xeb, 0x5d, 0x73, 0xf5, 0x2c, 0x1f, 0xe6, 0xf2, 0x23, 0x00, 0x00, 0xff,
	0xff, 0xce, 0xac, 0x59, 0x46, 0xae, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockServiceClient is the client API for BlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockServiceClient interface {
	GetMCBlockByNumber(ctx context.Context, in *BspBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	GetECBlockByNumber(ctx context.Context, in *BspBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
}

type blockServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlockServiceClient(cc *grpc.ClientConn) BlockServiceClient {
	return &blockServiceClient{cc}
}

func (c *blockServiceClient) GetMCBlockByNumber(ctx context.Context, in *BspBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/bsp_transaction.BlockService/GetMCBlockByNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockServiceClient) GetECBlockByNumber(ctx context.Context, in *BspBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/bsp_transaction.BlockService/GetECBlockByNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockServiceServer is the server API for BlockService service.
type BlockServiceServer interface {
	GetMCBlockByNumber(context.Context, *BspBlockRequest) (*BlockResponse, error)
	GetECBlockByNumber(context.Context, *BspBlockRequest) (*BlockResponse, error)
}

// UnimplementedBlockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlockServiceServer struct {
}

func (*UnimplementedBlockServiceServer) GetMCBlockByNumber(ctx context.Context, req *BspBlockRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCBlockByNumber not implemented")
}
func (*UnimplementedBlockServiceServer) GetECBlockByNumber(ctx context.Context, req *BspBlockRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetECBlockByNumber not implemented")
}

func RegisterBlockServiceServer(s *grpc.Server, srv BlockServiceServer) {
	s.RegisterService(&_BlockService_serviceDesc, srv)
}

func _BlockService_GetMCBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BspBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).GetMCBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bsp_transaction.BlockService/GetMCBlockByNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).GetMCBlockByNumber(ctx, req.(*BspBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockService_GetECBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BspBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).GetECBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bsp_transaction.BlockService/GetECBlockByNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).GetECBlockByNumber(ctx, req.(*BspBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bsp_transaction.BlockService",
	HandlerType: (*BlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMCBlockByNumber",
			Handler:    _BlockService_GetMCBlockByNumber_Handler,
		},
		{
			MethodName: "GetECBlockByNumber",
			Handler:    _BlockService_GetECBlockByNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockservice.proto",
}
