# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blockservice.proto',
  package='bsp_transaction',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x62lockservice.proto\x12\x0f\x62sp_transaction\"6\n\x0f\x42spBlockRequest\x12\x13\n\x0b\x42lockNumber\x18\x01 \x01(\x04\x12\x0e\n\x06Region\x18\x02 \x01(\t\"L\n\rBlockResponse\x12\x0f\n\x07Payload\x18\x01 \x01(\x0c\x12\x11\n\tSignature\x18\x02 \x01(\x0c\x12\x17\n\x0fSignatureHeader\x18\x03 \x01(\x0c\x32\xbe\x01\n\x0c\x42lockService\x12V\n\x12GetMCBlockByNumber\x12 .bsp_transaction.BspBlockRequest\x1a\x1e.bsp_transaction.BlockResponse\x12V\n\x12GetECBlockByNumber\x12 .bsp_transaction.BspBlockRequest\x1a\x1e.bsp_transaction.BlockResponseb\x06proto3'
)




_BSPBLOCKREQUEST = _descriptor.Descriptor(
  name='BspBlockRequest',
  full_name='bsp_transaction.BspBlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BlockNumber', full_name='bsp_transaction.BspBlockRequest.BlockNumber', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Region', full_name='bsp_transaction.BspBlockRequest.Region', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=93,
)


_BLOCKRESPONSE = _descriptor.Descriptor(
  name='BlockResponse',
  full_name='bsp_transaction.BlockResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Payload', full_name='bsp_transaction.BlockResponse.Payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Signature', full_name='bsp_transaction.BlockResponse.Signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SignatureHeader', full_name='bsp_transaction.BlockResponse.SignatureHeader', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['BspBlockRequest'] = _BSPBLOCKREQUEST
DESCRIPTOR.message_types_by_name['BlockResponse'] = _BLOCKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BspBlockRequest = _reflection.GeneratedProtocolMessageType('BspBlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _BSPBLOCKREQUEST,
  '__module__' : 'blockservice_pb2'
  # @@protoc_insertion_point(class_scope:bsp_transaction.BspBlockRequest)
  })
_sym_db.RegisterMessage(BspBlockRequest)

BlockResponse = _reflection.GeneratedProtocolMessageType('BlockResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKRESPONSE,
  '__module__' : 'blockservice_pb2'
  # @@protoc_insertion_point(class_scope:bsp_transaction.BlockResponse)
  })
_sym_db.RegisterMessage(BlockResponse)



_BLOCKSERVICE = _descriptor.ServiceDescriptor(
  name='BlockService',
  full_name='bsp_transaction.BlockService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=174,
  serialized_end=364,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMCBlockByNumber',
    full_name='bsp_transaction.BlockService.GetMCBlockByNumber',
    index=0,
    containing_service=None,
    input_type=_BSPBLOCKREQUEST,
    output_type=_BLOCKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetECBlockByNumber',
    full_name='bsp_transaction.BlockService.GetECBlockByNumber',
    index=1,
    containing_service=None,
    input_type=_BSPBLOCKREQUEST,
    output_type=_BLOCKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKSERVICE)

DESCRIPTOR.services_by_name['BlockService'] = _BLOCKSERVICE

# @@protoc_insertion_point(module_scope)
